#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ def get_external_domain_tls():
#@   if data.values.ingress_issuer:
#@     return "Enabled"
#@   else:
#@     return "Disabled"
#@   end
#@ end

#@ def get_external_scheme():
#@   if data.values.ingress.contour["default-tls-secret"]:
#@     return "https"
#@   else:
#@     return data.values.config.network["default-external-scheme"]
#@   end
#@ end

#@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata":{"name":"config-network"}})
---
#@overlay/match-child-defaults missing_ok=True
data:
  ingress-class: contour.ingress.networking.knative.dev
  certificate-class: cert-manager.certificate.networking.knative.dev
  namespace-wildcard-cert-selector: #@ data.values.config.network["namespace-wildcard-cert-selector"]
  domain-template: #@ data.values.config.network["domain-template"]
  external-domain-tls: #@ get_external_domain_tls()
  http-protocol: #@ data.values.config.network["http-protocol"]
  rollout-duration: #@ str(data.values.config.network["rollout-duration"])
  default-external-scheme: #@ get_external_scheme()
