#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata":{"name":"config-domain"}})
---
#@overlay/match-child-defaults missing_ok=True
data:
  #@yaml/text-templated-strings
  (@= data.values.config.domain.name @): ""
