#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if data.values.tls.certmanager.clusterissuer:

#@overlay/match by=overlay.subset({"metadata":{"name":"config-certmanager"}})
---
#@overlay/match-child-defaults missing_ok=True
data:
  #@yaml/text-templated-strings
  issuerRef: |
    kind: ClusterIssuer
    name: (@= data.values.tls.certmanager.clusterissuer @)

#@ end
