#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"metadata":{"name":"config-contour"}})
---
#@overlay/match-child-defaults missing_ok=True
data:

  #@ if/end data.values.ingress.contour["default-tls-secret"]:
  default-tls-secret: #@ data.values.ingress.contour["default-tls-secret"]

  #@yaml/text-templated-strings
  visibility: |
    ExternalIP:
      class: contour
      service: (@= data.values.ingress.contour.external.namespace @)/envoy
    ClusterLocal:
      class: contour
      service: (@= data.values.ingress.contour.internal.namespace @)/envoy
