#@ load("@ytt:data", "data")

#@ if data.values.policies.include:
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: knative-serving-verify-image
  annotations:
    policies.kyverno.io/title: Verify Image
    policies.kyverno.io/category: Software Supply Chain Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.9.0
    policies.kyverno.io/description: >-
      Using the Cosign project, this policy checks all container images used by this package
      to ensure they have been signed by verifying their signatures against the provided public key. 
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  rules:
    - name: verify-signature
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "gcr.io/knative-releases/knative.dev/*"
        attestors:
        - entries:
          - keyless:
              #! https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#verifying-image-signatures
              subject: "signer@knative-nightly.iam.gserviceaccount.com"
              issuer: "https://accounts.google.com"
#@ end
