apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: knative-serving.packages.kadras.io.0.0.0
spec:
  licenses:
  - Apache 2.0
  refName: knative-serving.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-knative-serving/releases
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: {}
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: knative-serving.packages.kadras.io
spec:
  categories:
  - serverless
  - deployment
  displayName: knative-serving
  longDescription: Knative Serving builds on Kubernetes to define and control the
    deployment of applications and functions as serverless containers.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: Solution for running serverless deployments on Kubernetes.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/package-for-knative-serving
    for community support.

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: knative-serving
spec:
  packageRef:
    refName: knative-serving.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
