apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - githubRelease:
      disableAutoChecksumValidation: true
      slug: knative/serving
      tag: knative-v1.12.0
    includePaths:
    - serving-core.yaml
    - serving-hpa.yaml
    path: serving
  - githubRelease:
      disableAutoChecksumValidation: true
      slug: knative-extensions/net-contour
      tag: knative-v1.12.1
    includePaths:
    - net-contour.yaml
    path: net-contour
  - githubRelease:
      disableAutoChecksumValidation: true
      slug: knative-extensions/net-certmanager
      tag: knative-v1.12.0
    includePaths:
    - net-certmanager.yaml
    path: net-cert-manager
  path: config/upstream
kind: Config
minimumRequiredVersion: 0.32.0
